language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
solution: ./Vatsim.NET.sln
script:
  - dotnet restore
  - dotnet build --configuration Release
  - dotnet test ./Vatsim.NET.Test/Vatsim.NET.Test.csproj --no-build